Side Effects and Inputs
=======================

## Looping a Launch
```{r}
blastoff <- function(x){
  while(x != 0){
    Sys.sleep(1)
    cat(x,"\n")
    x <- x-1
    }
  Sys.sleep(1)
  cat("BANANAS!!!")
  }

blastoff(5)
```

## Testing Human Response Times
```{r eval=FALSE}
responseTime <- function(N){
    readline("PRESS RETURN WHEN READY:")
    result <- rep(NA,N)
    interval<-c(.1)
    for(k in 1:N){
        before <- Sys.time()
        readline("PRESS RETURN:")
        after<-Sys.time()
        delay <- as.numeric(after-before)
        cat(rep("\n",20))
        result[k]<-delay
        a<-Sys.time()
        Sys.sleep(rexp(20,rate=1/2))
        b<-Sys.time()
        c<-as.numeric(b-a)
        interval<-c(interval,c)
    }
    latency <- result[1:N]
    finish <- data.frame(interval=interval[1:N],latency=latency)
    return(finish)
}
```

```{r}
load("/home/aweberg/NEW-CS121/latencyData.RData")
latencyData
plot(latencyData[[1]],latencyData[[2]],xlab="Time Interval",ylab="Response Time",main="Response Time vs. Time Interval")
```
As can be seen, there seems to be some correlation showing that the larger the time interval, the higher the response time.


## Elaboration
```{r eval=FALSE}
testLatency2 <- function(N) {
    result <- vector(length=N)
  wordLength <- round(runif(N, 1, 20)) 
  for (k in 1:N) {
  x <- sample(letters, wordLength[k])  
  word <- paste (x, collapse="")
  phrase <- paste("Type the word, '", word, "' ", sep=" ")
  command <- readline(phrase)
    Sys.sleep(runif(1,min=1,max=5))
    before <- Sys.time() 
  while(command !=word){
    command <- readline("Try Again")}
    readline("Press Enter:")
    after <- Sys.time()
  delay <- as.numeric(after-before)
    cat(rep("\n",20))
    result[k] <- delay
    }
table <- data.frame("Word Length" = WordLength, "Latency" = result )
return(table)
}
```

