Crossword
===========
```{r}
words <- readLines(url("http://dtkaplan.github.io/ScientificComputing/Syllabus/Daily/Day-07/word_list_moby_crossword-flat/word_list_moby_crossword.flat.txt"))

v1<-words[grepl("^.$",words)==TRUE]
length(v1)
```
```{r}
v2<-words[grepl("^..$",words)==TRUE]
length(v2)
```
```{r}
v3<-words[grepl("^...$",words)==TRUE]
length(v3)
```
```{r}
v4<-words[grepl("^....$",words)==TRUE]
length(v4)
```
```{r}
v5<-words[grepl("^.....$",words)==TRUE]
length(v5)
```
```{r}
v6<-words[grepl("^......$",words)==TRUE]
length(v6)

v7<-words[grepl("^.......$",words)==TRUE]
length(v7)

v8<-words[grepl("^........$",words)==TRUE]
length(v8)

v9<-words[grepl("^.........$",words)==TRUE]
length(v9)

v10<-words[grepl("^..........$",words)==TRUE]
length(v10)

v11<-words[grepl("^...........$",words)==TRUE]
length(v11)

v12<-words[grepl("^............$",words)==TRUE]
length(v12)

v13<-words[grepl("^.............$",words)==TRUE]
length(v13)

v14<-words[grepl("^..............$",words)==TRUE]
length(v14)

v15<-words[grepl("^...............$",words)==TRUE]
length(v15)

v16<-words[grepl("^................$",words)==TRUE]
length(v16)

v17<-words[grepl("^.................$",words)==TRUE]
length(v17)

v18<-words[grepl("^..................$",words)==TRUE]
length(v18)

v19<-words[grepl("^...................$",words)==TRUE]
length(v19)

v20<-words[grepl("^....................$",words)==TRUE]
length(v20)

v21<-words[grepl("^.....................$",words)==TRUE]
length(v21)

v22<-words[grepl("^......................$",words)==TRUE]
length(v22)

```


```{r eval=FALSE}

wordLength<-function(x){
  list<-c()
  for(k in 1:length(words)){
    a<-strsplit(words[k],"")
    b<-a[[1]]
    c<-length(b)==x
    list<-c(list,c)}
  d<-which(list==TRUE)
  return(length(d))
  }

wordLength(2)

wordLength2 <- function(x){
  if x==1{v=""}|
  if x==2{v="."} 
  list<-c("")
```
v20<-words[grepl("^....................$",words)==TRUE]
length(v20)
