November 5
===========


```{r}
x <- seq(0,1,length=101)
plot(1:2,ylim=c(0,5),xlim=c(0,1),xlab="x",ylab="Prob Density",type="n")
lines(x,dbeta(x,shape1=1,shape2=2),lwd=1)
lines(x,dbeta(x,1,4),lwd=2)
lines(x,dbeta(x,4,2),lwd=3)

```

```{r}
drawBeta <- function(a,b,...){
  x <- seq(0,1,length=101)
  plot(1:2,ylim=c(0,5),xlim=c(0,1),xlab="x",ylab="Prob Density",type="n")
  return(lines(x,dbeta(x,a,b),...))
  }

drawBeta(4,2,col="red",lwd=5)

```


```{r eval=FALSE}
manipulate({drawBeta(a,b,col=color,lwd=width)}, ## must do this in the console
+            a=slider(0,5,initial=1,label="a",step=.2),
+            b=slider(0,5,initial=2,label="b",step=.2),
+            color=picker(as.list(colors()),initial="purple"),
+            width=slider(0,10,initial=3,label="width",step=.1))
```

```{r eval=FALSE}
betaApp <- function(pts){
  manipulate({drawBeta(a,b,col=color,lwd=width); ## must do this in the console
             points(pts,rep(0,length(pts)))},
             a=slider(0,5,initial=1,label="a",step=.2),
             b=slider(0,5,initial=2,label="b",step=.2),
             color=picker(as.list(colors()),initial="purple"),
             width=slider(0,10,initial=3,label="width",step=.1))
  }

betaApp(runif(50))
```