Crosswords-and-Scrabble
======================

```{r}
words <- readLines(url("http://dtkaplan.github.io/ScientificComputing/Syllabus/Daily/Day-07/word_list_moby_crossword-flat/word_list_moby_crossword.flat.txt"))
```
## Summarizing the List
#### Report of Word Lengths
(Slow version)
```{r eval=FALSE}
wordLength <- function(x){
  list<-c()
  a <- sapply(words,nchar)
  for(k in 1:length(words)){
    list<- c(list,a[[k]] == x)
    }
  return(sum(list))
  }
wordLength(3)
```
(Fast version)  
```{r eval=FALSE}  
wordLength <- function(x){
  list<-c()
  a <- sapply(words,nchar)
  for(k in 1:length(words)){
    if(a[[k]]==x){list<-c(list,a[[k]])}
    else{}
    }
  return(length(list))
  }  
```
```{r}
## 1
wordLength(1)
## 2
wordLength(2)
## 3
wordLength(3)
## 4
wordLength(4)
## 5
wordLength(5)
## 6
wordLength(6)
## 7
wordLength(7)
## 8
wordLength(8)
## 9
wordLength(9)
## 10
wordLength(10)
## 11
wordLength(11)
## 12
wordLength(12)
## 13
wordLength(13)
## 14
wordLength(14)
## 15
wordLength(15)
## 16
wordLength(16)
## 17
wordLength(17)
## 18
wordLength(18)
## 19
wordLength(19)
## 20
wordLength(20)
## 21
wordLength(21)
## 22
wordLength(22)
```

#### 100 Longest Words
Unfortunately, there are not 100 longest words.  There are 204 of length 17 and above, or else 72 of 18 and above.
```{r eval=FALSE}
wordList <- function(x){
  list<-c()
  a <- sapply(words,nchar)
  for(k in 1:length(words)){
    if(a[[k]]==x){list<-c(list,words[k])}
    else{}
    }
  return(list)
  } 
hunWords<-c(wordList(21),wordList(20),wordList(19),wordList(18),wordList(17))
```
```{r}
length(hunWords)
hunWords

```

#### Number of Words Beginning with Each Letter
```{r eval=FALSE}
## A
length(words[grepl("^a",words)==TRUE])
## B
length(words[grepl("^b",words)==TRUE])
## C
length(words[grepl("^c",words)==TRUE])
## D
length(words[grepl("^d",words)==TRUE])
## E
length(words[grepl("^e",words)==TRUE])
## F
length(words[grepl("^f",words)==TRUE])
## G
length(words[grepl("^g",words)==TRUE])
## H
length(words[grepl("^h",words)==TRUE])
## I
length(words[grepl("^i",words)==TRUE])
## J
length(words[grepl("^j",words)==TRUE])
## K
length(words[grepl("^k",words)==TRUE])
## L
length(words[grepl("^l",words)==TRUE])
## M
length(words[grepl("^m",words)==TRUE])
## N
length(words[grepl("^n",words)==TRUE])
## O
length(words[grepl("^o",words)==TRUE])
## P
length(words[grepl("^p",words)==TRUE])
## Q
length(words[grepl("^q",words)==TRUE])
## R
length(words[grepl("^r",words)==TRUE])
## S
length(words[grepl("^s",words)==TRUE])
## T
length(words[grepl("^t",words)==TRUE])
## U
length(words[grepl("^u",words)==TRUE])
## V
length(words[grepl("^v",words)==TRUE])
## W
length(words[grepl("^w",words)==TRUE])
## X
length(words[grepl("^x",words)==TRUE])
## Y
length(words[grepl("^y",words)==TRUE])
## Z
length(words[grepl("^z",words)==TRUE])
```

#### "Q" Without "U"
```{r eval=FALSE}
noU<-words[grepl("q[^u]",words)==TRUE]
noU
```

## Crossword Helper
```{r eval=FALSE}
crossword <- function(x){
  a <- grepl(x,words)
  return(words[a])
}

crossword("^.t..r..$")
```

## A Better Crossword Helper
Best one so far...
```{r}

crosswordPattern<-function(x,y,w,z,v){
  list<-1:v
  list2<-gsub(y,x,list)
  list22<-gsub(z,w,list2)
  list3<-gsub("1",".",list2)
  list4<-gsub("2",".",list3)
  list5<-gsub("3",".",list4)
  list6<-gsub("4",".",list5)
  list7<-gsub("5",".",list6)
  list8<-gsub("6",".",list7)
  list9<-gsub("7",".",list8)
  list10<-gsub("8",".",list9)
  list11<-gsub("9",".",list10)
  list12<-c("^",list11,"$")
  pattern<-paste(list12,collapse="")
  a <- grepl(pattern,words)
  return(words[a])
  }

crosswordPattern("x",1,"s",7,7)

```
work in progress...
```{r}
crosswordPattern<-function(x,y,v){
  list<-c()
  for(k in 1:v){
    list<-c(list,".")
  }
  list2<-gsub(y,x,list)
  list3<-gsub("1",".",list2)
  list4<-gsub("2",".",list3)
  list5<-gsub("3",".",list4)
  list6<-gsub("4",".",list5)
  list7<-gsub("5",".",list6)
  list8<-gsub("6",".",list7)
  list9<-gsub("7",".",list8)
  list10<-gsub("8",".",list9)
  list11<-gsub("9",".",list10)
  list12<-gsub("10",".",list11)
  list13<-gsub("11",".",list12)
  list14<-gsub("12",".",list13)
  list15<-gsub("13",".",list14)
  list16<-gsub("14",".",list15)
  list17<-gsub("15",".",list16)
  list18<-gsub("16",".",list17)
  list19<-gsub("17",".",list18)
  list20<-gsub("18",".",list19)
  list21<-gsub("19",".",list20)
  list22<-gsub("20",".",list21)
  list23<-gsub("21",".",list22)
  list24<-c("^",list23,"$")
  pattern<-paste(list24,collapse="")
  a <- grepl(pattern,words)
  return(words[a])
  }

```


