November7
========

```{r eval=FALSE}
ourTree <- list("The World",
  			list("Non-Continental", list("Fiji","New Zealand")),
				list("Continental",
               	  	  list("Africa", list("Ghana", "Kenya", "Morocco")),
                      list("Americas",
                      		list("North", list("Canada","Mexico")),
                            list("South",list("Chile","Bolivia"))),
                      list("Antarctica"),
                      list("Asia", 
                      		list("Thailand", "Bhutan", "Mongolia")),
                      list("Australia"),
					  list("Europe",
                    		list("Slovakia", "Romania")))
```

```{r}
myI<-bootstrapPage(
  div(class='jumbotron masthead',
      h1('The Title of My Page'),
      p('This will be the very polite introduction to my page')
  ),
  div(class='row span12',
    div(class='span4',
        h3("In the first block")
    ),
    div(class='span3',
        h4("'I am here, too")
        h2('Big Brother')
    )
  )
```  